# Lightweight  image
image: alpine:latest

# Job publish site
pages:
  stage: deploy
  script:
    # Create folder .public
    - mkdir -p .public
    # Copy file & folder excluding .gitlab-ci.yml 
    - shopt -s extglob
    - cp -r !( .public|.git|.gitlab-ci.yml ) .public
  artifacts:
    paths:
      - .public
  only:
    - main 
